sudo: required
services:
- docker
before_install:
  - echo $KEY
# - gem install bundler
# - docker build -t reactapp -f dev.Dockerfile .
# script:
# - docker run reactapp npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: react
#   end: React-env
#   bucket_name: elasticbeanstalk-us-east-2-416297931845
#   bucker_path: react
#   on:
#     branch: dev
#   access_key_id: $ID
#   secret_access_key:
#     secure: $KEY
