sudo: required

language: ruby

services:
  - docker

before_install:
  - gem install bundler
  - docker build -t reactapp -f dev.Dockerfile .

script:
  - docker run reactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: react
  env: React-env
  bucket_name: elasticbeanstalk-us-east-2-416297931845
  bucker_path: react
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
