sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t farhan687/reactapp -f dev.Dockerfile .

scrpit:
  - docker run farhan687/reactapp npm run test -- --coverage
