version: '3'
services:
  # First container which will take care of app development
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  
      # Second container which will take care of app test
  test:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
